-- Find the item that has minimum weight
SELECT MIN(WEIG-- HT) AS MINITEM_WEIGHT FROM ITEMS;

-- Find the different warehouses in “Pune”.
SELECT W.WNAME, C.CITY FROM warehouses W, CITIES C WHERE W.CITY_ID = C.CITY_ID AND C.CITY ='PUNE';

-- Find the details of items ordered by a customer “JIMISH GAJJAR”
SELECT C.CNAME, O.ONO, O.ODATE, I.DESCRIPTION, IO.ITEMNO FROM ITEMS_ORDERS IO, CUSTOMER C, ORDERS O, ITEMS I WHERE O.CNO = C.CNO AND IO.ITEMNO = I.ITEMNO AND CNAME = 'JIMISH GAJJAR' GROUP BY IO.ITEMNO;

-- Find a Warehouse which has maximum stores.
SELECT * FROM WAREHOUSES WHERE WID = (SELECT WID FROM STORES GROUP BY WID ORDER BY COUNT(*) DESC LIMIT 1);

-- Find an item which is ordered for a minimum number of times
SELECT * FROM ITEMS WHERE ITEMNO = (SELECT ITEMNO FROM ITEMS_ORDERS GROUP BY ITEMNO ORDER BY COUNT(*) LIMIT 1);

-- Find the detailed orders given by each customer.
SELECT C.CUSTOMER_NAME, I.DESCRIPTION, I.WEIGHT, I.COST, O.ORDER_DATE, C.CUSTOMER_CITY FROM ORDERS O
INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
INNER JOIN ITEMS_ORDERS IOS ON IOS.ORDER_ID = O.ORDER_ID
INNER JOIN ITEMS I ON I.ITEM_ID = IOS.ITEM_ID;